name: Codacy Review Labeler

on:
  pull_request:
    types: [opened, ready_for_review, edited, reopened]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # needs issues: OR pull-requests: read & write to create labels on a PR
    steps:
      - name: Add Codacy label
        uses: codacy/codacy-review-label-action@49e26d7e573128eeb18de157bffd8fe858dd35ba
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # default GH actions token
        with:
          create-label: true # optional
          label-color: "050B1A" # optional
          include-drafts: false # optional, more details below
          bots: false # optional
#          required-title-keywords: "^feat:, docs" # optional
#          exclude-title-keywords: "revert, ^draft, ^wip" # optional
